### ISSUE TITLE
Help not working in webkit browsers (Safari, Midori, Epiphany)

### ISSUE THREAD

**Issue by kosarko** [ufal/perl-pmltq-web#64] opened 2016-10-07 12:59 UTC
There are empty boxes instead of examples on help page. Go to https://lindat.mff.cuni.cz/services/pmltq/#!/treebank/hamledt_la/help in either Safari, Midori or other webkit browser

There's an error logged to console

```
Error: Invalid regular expression: regular expression too large
RegExp@[native code]
a@https://lindat.mff.cuni.cz/services/pmltq/2bd8882d21ba2eff84c5-pmltq.js:50:38350
o@https://lindat.mff.cuni.cz/services/pmltq/2bd8882d21ba2eff84c5-pmltq.js:5:6957
getTokenizer@https://lindat.mff.cuni.cz/services/pmltq/2bd8882d21ba2eff84c5-pmltq.js:6:14442
```

**Comment by matyaskopp** [comment] 2017-01-17 13:41
duplicate of issue #51

**Closed by matyaskopp** 2017-01-17 13:41 UTC
Labels: bug
