### ISSUE TITLE
Permanent links

### ISSUE THREAD

**Issue by dan-zeman** [ufal/perl-pmltq-web#54] opened 2015-11-19 19:28 UTC
When I click on the "Permanent link" button, the URL I get has repeated prefix:

http://hdl.handle.net/http://hdl.handle.net/11346/PMLTQ-CJSG

Otherwise it works (after I remove the repeated part).

When I click on the button twice with the same treebank and query, I get two different links. Not sure whether it is intended.

**Comment by m1ch4ls** [comment] 2015-11-23 10:25
It is fixed in bbfa0538c0e0beda24158bba5f7b60b7caa83daa

The cause was change in underlying API.

> When I click on the button twice with the same treebank and query, I get two different links. Not sure whether it is intended.

This is intended, although I would prefer having the same permalink for the same query. It kind of make more sense to me. I maybe implement feature that once the permalink is generated it won't be generated again for the same session. So one user gets the same link for the same query.

**Closed by m1ch4ls** 2015-11-23 10:25 UTC
Labels: bug
